In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [3]:
dataset = pd.read_csv('CKD.csv')
dataset

,age,bp,sg,al,su,rbc,pc,pcc,ba,bgr,...,pcv,wc,rc,htn,dm,cad,appet,pe,ane,classification
0,2.000000,76.459948,c,3.0,0.0,normal,abnormal,notpresent,notpresent,148.112676,...,38.868902,8408.191126,4.705597,no,no,no,yes,yes,no,yes
1,3.000000,76.459948,c,2.0,0.0,normal,normal,notpresent,notpresent,148.112676,...,34.000000,12300.000000,4.705597,no,no,no,yes,poor,no,yes
2,4.000000,76.459948,a,1.0,0.0,normal,normal,notpresent,notpresent,99.000000,...,34.000000,8408.191126,4.705597,no,no,no,yes,poor,no,yes
3,5.000000,76.459948,d,1.0,0.0,normal,normal,notpresent,notpresent,148.112676,...,38.868902,8408.191126,4.705597,no,no,no,yes,poor,yes,yes
4,5.000000,50.000000,c,0.0,0.0,normal,normal,notpresent,notpresent,148.112676,...,36.000000,12400.000000,4.705597,no,no,no,yes,poor,no,yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
394,51.492308,70.000000,a,0.0,0.0,normal,normal,notpresent,notpresent,219.000000,...,37.000000,9800.000000,4.400000,no,no,no,yes,poor,no,yes
395,51.492308,70.000000,c,0.0,2.0,normal,normal,notpresent,notpresent,220.000000,...,27.000000,8408.191126,4.705597,yes,yes,no,yes,poor,yes,yes
396,51.492308,70.000000,c,3.0,0.0,normal,normal,notpresent,notpresent,110.000000,...,26.000000,9200.000000,3.400000,yes,yes,no,poor,poor,no,yes
397,51.492308,90.000000,a,0.0,0.0,normal,normal,notpresent,notpresent,207.000000,...,38.868902,8408.191126,4.705597,yes,yes,no,yes,poor,yes,yes
398,51.492308,80.000000,a,0.0,0.0,normal,normal,notpresent,notpresent,100.000000,...,53.000000,8500.000000,4.900000,no,no,no,yes,poor,no,no

In [4]:
dataset=pd.get_dummies(dataset,drop_first=True)
dataset = dataset.astype(int)
pd.set_option('display.max_columns', None)
dataset

,age,bp,al,su,bgr,bu,sc,sod,pot,hrmo,pcv,wc,rc,sg_b,sg_c,sg_d,sg_e,rbc_normal,pc_normal,pcc_present,ba_present,htn_yes,dm_yes,cad_yes,appet_yes,pe_yes,ane_yes,classification_yes
0,2,76,3,0,148,57,3,137,4,12,38,8408,4,0,1,0,0,1,0,0,0,0,0,0,1,1,0,1
1,3,76,2,0,148,22,0,137,4,10,34,12300,4,0,1,0,0,1,1,0,0,0,0,0,1,0,0,1
2,4,76,1,0,99,23,0,138,4,12,34,8408,4,0,0,0,0,1,1,0,0,0,0,0,1,0,0,1
3,5,76,1,0,148,16,0,138,3,8,38,8408,4,0,0,1,0,1,1,0,0,0,0,0,1,0,1,1
4,5,50,0,0,148,25,0,137,4,11,36,12400,4,0,1,0,0,1,1,0,0,0,0,0,1,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
394,51,70,0,0,219,36,1,139,3,12,37,9800,4,0,0,0,0,1,1,0,0,0,0,0,1,0,0,1
395,51,70,0,2,220,68,2,137,4,8,27,8408,4,0,1,0,0,1,1,0,0,1,1,0,1,0,1,1
396,51,70,3,0,110,115,6,134,2,9,26,9200,3,0,1,0,0,1,1,0,0,1,1,0,0,0,0,1
397,51,90,0,0,207,80,6,142,5,8,38,8408,4,0,0,0,0,1,1,0,0,1,1,0,1,0,1,1
398,51,80,0,0,100,49,1,140,5,16,53,8500,4,0,0,0,0,1,1,0,0,0,0,0,1,0,0,0

In [5]:
dataset["classification_yes"].value_counts()

classification_yes
1    249
0    150
Name: count, dtype: int64

In [6]:
dataset.columns

Index(['age', 'bp', 'al', 'su', 'bgr', 'bu', 'sc', 'sod', 'pot', 'hrmo', 'pcv',
       'wc', 'rc', 'sg_b', 'sg_c', 'sg_d', 'sg_e', 'rbc_normal', 'pc_normal',
       'pcc_present', 'ba_present', 'htn_yes', 'dm_yes', 'cad_yes',
       'appet_yes', 'pe_yes', 'ane_yes', 'classification_yes'],
      dtype='object')

In [7]:
independent=dataset[['age', 'bp', 'al', 'su', 'bgr', 'bu', 'sc', 'sod', 'pot', 'hrmo', 'pcv',
       'wc', 'rc', 'sg_b', 'sg_c', 'sg_d', 'sg_e', 'rbc_normal', 'pc_normal',
       'pcc_present', 'ba_present', 'htn_yes', 'dm_yes', 'cad_yes',
       'appet_yes', 'pe_yes', 'ane_yes',]]
independent

,age,bp,al,su,bgr,bu,sc,sod,pot,hrmo,pcv,wc,rc,sg_b,sg_c,sg_d,sg_e,rbc_normal,pc_normal,pcc_present,ba_present,htn_yes,dm_yes,cad_yes,appet_yes,pe_yes,ane_yes
0,2,76,3,0,148,57,3,137,4,12,38,8408,4,0,1,0,0,1,0,0,0,0,0,0,1,1,0
1,3,76,2,0,148,22,0,137,4,10,34,12300,4,0,1,0,0,1,1,0,0,0,0,0,1,0,0
2,4,76,1,0,99,23,0,138,4,12,34,8408,4,0,0,0,0,1,1,0,0,0,0,0,1,0,0
3,5,76,1,0,148,16,0,138,3,8,38,8408,4,0,0,1,0,1,1,0,0,0,0,0,1,0,1
4,5,50,0,0,148,25,0,137,4,11,36,12400,4,0,1,0,0,1,1,0,0,0,0,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
394,51,70,0,0,219,36,1,139,3,12,37,9800,4,0,0,0,0,1,1,0,0,0,0,0,1,0,0
395,51,70,0,2,220,68,2,137,4,8,27,8408,4,0,1,0,0,1,1,0,0,1,1,0,1,0,1
396,51,70,3,0,110,115,6,134,2,9,26,9200,3,0,1,0,0,1,1,0,0,1,1,0,0,0,0
397,51,90,0,0,207,80,6,142,5,8,38,8408,4,0,0,0,0,1,1,0,0,1,1,0,1,0,1
398,51,80,0,0,100,49,1,140,5,16,53,8500,4,0,0,0,0,1,1,0,0,0,0,0,1,0,0

In [8]:
dependent=dataset[["classification_yes"]]
dependent

     classification_yes
0                     1
1                     1
2                     1
3                     1
4                     1
..                  ...
394                   1
395                   1
396                   1
397                   1
398                   0

[399 rows x 1 columns]

In [9]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(independent, dependent, test_size = 1/3, random_state = 0)

In [10]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train_= sc.fit_transform(X_train)
X_test_= sc.transform(X_test)

In [11]:
from sklearn.linear_model import LogisticRegression

In [12]:
from sklearn.model_selection import GridSearchCV

param_grid = {'solver':['newton-cg', 'lbfgs', 'liblinear', 'saga'],
             'penalty':['l2']} 



grid = GridSearchCV(LogisticRegression(), param_grid, refit = True, verbose = 3,n_jobs=-1,scoring='f1_weighted') 
   

grid.fit(X_train, y_train)

Fitting 5 folds for each of 4 candidates, totalling 20 fits

C:\Users\Navaneethan\anaconda3\Lib\site-packages\sklearn\utils\validation.py:1184: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Navaneethan\anaconda3\Lib\site-packages\scipy\optimize\_linesearch.py:466: LineSearchWarning: The line search algorithm did not converge
  warn('The line search algorithm did not converge', LineSearchWarning)
C:\Users\Navaneethan\anaconda3\Lib\site-packages\scipy\optimize\_linesearch.py:314: LineSearchWarning: The line search algorithm did not converge
  warn('The line search algorithm did not converge', LineSearchWarning)
C:\Users\Navaneethan\anaconda3\Lib\site-packages\sklearn\utils\optimize.py:211: ConvergenceWarning: newton-cg failed to converge. Increase the number of iterations.
  warnings.warn(

GridSearchCV(estimator=LogisticRegression(), n_jobs=-1,
             param_grid={'penalty': ['l2'],
                         'solver': ['newton-cg', 'lbfgs', 'liblinear', 'saga']},
             scoring='f1_weighted', verbose=3)

In [13]:
re=grid.cv_results_

grid_predictions = grid.predict(X_test) 
   

from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, grid_predictions)

 
from sklearn.metrics import classification_report
clf_report = classification_report(y_test, grid_predictions)

In [14]:
from sklearn.metrics import f1_score
f1_macro=f1_score(y_test,grid_predictions,average='weighted')
print("The f1_macro value for best parameter {}:".format(grid.best_params_),f1_macro)

The f1_macro value for best parameter {'penalty': 'l2', 'solver': 'newton-cg'}: 1.0

In [15]:
print("The confusion Matrix:\n",cm)

The confusion Matrix:
 [[51  0]
 [ 0 82]]

In [16]:
print("The report:\n",clf_report)

The report:
               precision    recall  f1-score   support

           0       1.00      1.00      1.00        51
           1       1.00      1.00      1.00        82

    accuracy                           1.00       133
   macro avg       1.00      1.00      1.00       133
weighted avg       1.00      1.00      1.00       133

In [17]:
from sklearn.metrics import roc_auc_score

roc_auc_score(y_test,grid.predict_proba(X_test)[:,1])

1.0

In [ ]:
age=float(input("Age:"))
bp=float(input("bp:"))
al=float(input("al:"))
su=float(input("su:"))
bgr=float(input("bgr:"))
bu=float(input("bu:"))
sc=float(input("sc:"))
sod=float(input("sod:"))
pot=float(input("pot:"))
hrmo=float(input("hrmo:"))
pcv=float(input("pcv:"))
wc=float(input("wc:"))
rc=float(input("rc:"))
sg_b=int(input("sg_b:"))
sg_c=int(input("sg_c:"))
sg_d=int(input("sg_d:"))
sg_e=int(input("sg_e:"))
rbc_normal=int(input("rbc_normal:"))
pcc_present=int(input("pcc_present:"))
pc_normal=int(input("pc_normal:"))
ba_present=int(input("ba_present:"))
htn_yes=int(input("htn_yes:"))
dm_yes=int(input("dm_yes:"))
cad_yes=int(input("cad_yes:"))
appet_yes=int(input("appet_yes:"))
pe_yes=int(input("pe_yes:"))
ane_yes=int(input("ane_yes:"))

In [ ]:
Future_Prediction = grid.predict([[age, bp, al, su, bgr, bu, sc, sod, pot, hrmo, pcv,
                                   wc, rc, sg_b, sg_c, sg_d, sg_e, rbc_normal,pcc_present, pc_normal,ba_present, htn_yes, dm_yes, cad_yes,
                                   appet_yes, pe_yes, ane_yes]])
print("Future_Prediction={}".format(Future_Prediction))